/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhangjunling_example_androidmediaprojects_view_NativeTextureSurfaceView */

#ifndef _Included_com_zhangjunling_example_androidmediaprojects_view_NativeTextureSurfaceView
#define _Included_com_zhangjunling_example_androidmediaprojects_view_NativeTextureSurfaceView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeTextureSurfaceView
 * Method:    start
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeTextureSurfaceView_start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeTextureSurfaceView
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeTextureSurfaceView_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeTextureSurfaceView
 * Method:    requestSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeTextureSurfaceView_requestSurfaceChanged
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeTextureSurfaceView
 * Method:    requestExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeTextureSurfaceView_requestExit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
