/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView */

#ifndef _Included_com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView
#define _Included_com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView_start
  (JNIEnv *, jobject);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView
 * Method:    requestInitEGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView_requestInitEGL
  (JNIEnv *, jobject);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView
 * Method:    requestSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView_requestSurfaceCreated
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView
 * Method:    requestSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView_requestSurfaceChanged
  (JNIEnv *, jobject,jobject, jint, jint);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView
 * Method:    requestOnDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView_requestOnDrawFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView
 * Method:    requestExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeEGLSurfaceView_requestExit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
