/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhangjunling_example_androidmediaprojects_render_GraphicalRender */

#ifndef _Included_com_zhangjunling_example_androidmediaprojects_render_GraphicalRender
#define _Included_com_zhangjunling_example_androidmediaprojects_render_GraphicalRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhangjunling_example_androidmediaprojects_render_GraphicalRender
 * Method:    onSurfaceCrerated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_render_GraphicalRender_onSurfaceCrerated
  (JNIEnv *, jobject,jstring ,jstring );

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_render_GraphicalRender
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_render_GraphicalRender_onSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_render_GraphicalRender
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_render_GraphicalRender_onDrawFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
