/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhangjunling_example_androidmediaprojects_view_NativeSurfaceView */

#ifndef _Included_com_zhangjunling_example_androidmediaprojects_view_NativeSurfaceView
#define _Included_com_zhangjunling_example_androidmediaprojects_view_NativeSurfaceView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeSurfaceView
 * Method:    start
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeSurfaceView_start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeSurfaceView
 * Method:    setWindow
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeSurfaceView_setWindow
  (JNIEnv *, jobject,jobject);

/*
 * Class:     com_zhangjunling_example_androidmediaprojects_view_NativeSurfaceView
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_example_androidmediaprojects_view_NativeSurfaceView_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
