/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhangjunling_appaudio_audio_encode_natived_AudioFFmpegEncoder */

#ifndef _Included_com_zhangjunling_appaudio_audio_encode_natived_AudioFFmpegEncoder
#define _Included_com_zhangjunling_appaudio_audio_encode_natived_AudioFFmpegEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhangjunling_appaudio_audio_encode_natived_AudioFFmpegEncoder
 * Method:    init
 * Signature: (IIIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zhangjunling_appaudio_audio_1encode_natived_AudioFFmpegEncoder_init
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring);

/*
 * Class:     com_zhangjunling_appaudio_audio_encode_natived_AudioFFmpegEncoder
 * Method:    encode
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_appaudio_audio_1encode_natived_AudioFFmpegEncoder_encode
  (JNIEnv *, jobject, jshortArray , jint);

/*
 * Class:     com_zhangjunling_appaudio_audio_encode_natived_AudioFFmpegEncoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_appaudio_audio_1encode_natived_AudioFFmpegEncoder_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
