/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhangjunling_appaudio_OpenSLRecordActivity */

#ifndef _Included_com_zhangjunling_appaudio_OpenSLRecordActivity
#define _Included_com_zhangjunling_appaudio_OpenSLRecordActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhangjunling_appaudio_OpenSLRecordActivity
 * Method:    opensl_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_appaudio_OpenSLRecordActivity_opensl_1start
  (JNIEnv *, jobject);

/*
 * Class:     com_zhangjunling_appaudio_OpenSLRecordActivity
 * Method:    opensl_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhangjunling_appaudio_OpenSLRecordActivity_opensl_1stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
